---
synapse:
  prissmm: 
    id: syn22684834
    name: PRISSM Documentation Versions
    type: table
    description: PRISSMM data dictionary versions by cohort and date
  sor: 
    id: syn22294851
    name: GENIE_BPC_Release_Scope
    type: xlsx
    description: Description of all data elements by MSK stats team 
  genie_patient: 
    id: syn7517669
    name: Patient Clinical Database
    type: table
    description: Main GENIE reference of patient IDs
  genie_sample: 
    id: syn7517674
    name: Sample Clinical Database
    type: table
    description: Main GENIE reference of sample IDs
  version_date: 
    id: syn25837005
    name: Previous Upload Tracking
    type: table
    description: Date of previous upload by cohort
  version_release: 
    id: syn27628075
    name: Release Information
    type: table
    description: Release metadata and link to clinical data file folders.
  tables_view: 
    id: syn21446696
    name: Data table Information
    type: table
    description: All tables of raw data elements for GENIE BPC
  test_project:
    id: syn25921894
    name: hhz_test_project
    type: project
    description: Project to which test script can write temporary fixtures
  test_table_view:
    id: syn26215556
    name: test_view
    type: table
    description: Table view in test project for testing
  rm_pat:
    id: syn25998970
    name: BPC Patient Retraction
    type: table
    description: BPC samples to remove from BPC cohorts
  rm_sam:
    id: syn25779833
    name: BPC Sample Retraction
    type: table
    description: BPC samples to remove from BPC cohorts
  target_count:
    id: syn26228746
    name: Case Selection Counts
    type: table
    description: Target cohort counts by site
  release:
    id: syn21241322
    name: AACR Project GENIE BPC Data
    type: folder
    description: umbrella folder for all BPC releases
  drug:
    id: syn21446703
    name: Ca Directed Drugs
    type: table
    description: BPC drug regimen data
  relationship:
    id: syn26119155
    name: hemonc_cc_relationship
    type: table
    description: HemOnc ontology relationship table
  concept:
    id: syn26119153
    name: hemonc_cc_concept
    type: table
    description: HemOnc concept relationship table
  map:
    id: syn26125434
    name: hemonc_map_bpc
    type: table
    description: Table mapping BPC drug names to HemOnc ontology drug names
  curation:
    id: syn21446698
    name: Curation and QA
    type: table
    description: BPC Internal table with curation metadata
table_name:
  patient_id: Patient Characteristics
  sample_id: Cancer Panel Test
column_name:
  patient_id: record_id
  sample_id: cpt_genie_sample_id
  instrument: redcap_repeat_instrument
  instance: redcap_repeat_instance
  oncotree_code: cpt_oncotree_code
instrument_name:
  panel: cancer_panel_test
file_name:
  patient_file: patient_level_dataset.csv
  sample_file: cancer_panel_test_level_dataset.csv
maps:
  data_type:
    character: character
    datetime: character
    double: numeric
    integer: numeric
    logical: numeric
    numeric: numeric
  drug:
    investigational_drug: 49135
    ct_yes: 1
noninteger_values:
  age_at_seq_report:
  - '>32485'
  - 'Unknown'
  - '>89'
thresholds:
  fraction_missing: 0.05
constants:
  sage: SAGE
uploads:
  NSCLC:
    DFCI:
      data1: syn25582436
      header1: syn25582427
    MSK:
      data1: syn25557012
    UHN:
      data1: syn25686838
    VICC:
      data1: syn25579921
    SAGE:
      data1: syn27542392
  BrCa:
    DFCI:
      data1: syn26160187
      header1: syn25981842
      data2: syn26160184
      header2: syn25981841
    MSK:
      data1: syn24202045
    VICC:
      data1: syn24201984
    SAGE:
      data1: syn27541333
  PANC:
    DFCI:
      data1: syn25544638
      header1: syn25544639
    MSK:
      data1: syn25541828
    UHN:
      data1: syn26033209
    VICC:
      data1: syn25541702
    SAGE:
      data1: syn27538210
  Prostate:
    DFCI:
      data1: syn26230815
      header1: syn25592217
    MSK:
      data1: syn26230493
    UHN:
      data1: syn26212729
    VICC:
      data1: syn26231094
    SAGE:
      data1: syn27542446
  CRC:
    DFCI:
      data1: syn25961098
      header1: syn25961099
    MSK:
      data1: syn25953196
    VICC:
      data1: syn25961124
    SAGE:
      data1: syn27541444
  BLADDER:
    DFCI:
      data1: syn26250078
      header1: syn26250090
    MSK:
      data1: syn26250083
    UHN:
      data1: syn26250084
    VICC:
      data1: syn26250085
    SAGE:
      data1: syn27541023
output:
  BLADDER: syn26709456
  BrCa: syn25872288
  CRC: syn25878117
  NSCLC: syn25872287
  PANC: syn25882184
  Prostate: syn25976290
report:
  upload:
  - 44
  - 45
  - 49
  - 3
  - 4
  - 5
  - 6
  - 1
  - 2
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 26
  - 27
  - 28
  - 33
  - 34
  - 42
  - 46
  - 47
  - 48
  - 50
  - 51
  - 52
  - 54
  - 55
  table:
  - 7
  - 9
  - 12
  - 13
  - 14
  - 24
  - 25
  - 26
  - 27
  - 35
  - 53
  comparison:
  - 3
  - 4
  - 5
  - 6
  - 15
  - 16
  - 36
  - 37
  - 38
  - 39
  - 40
  release:
  - 3
  - 4
  - 5
  - 6
  - 15
  - 16
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  masking:
  - 44
  - 45
  - 29
  - 30
  - 31
  - 32
  - 43
checks:
  1:
    implemented: 1
    deprecated: 0
    level: warning
    label: col_import_template_added
    description: Column found in file upload but not import template.
    action: Please remove column from upload file.
  2:
    implemented: 1
    deprecated: 0
    level: warning
    label: col_import_template_removed
    description: Column found in import template but not file upload.
    action: Please confirm that column has no relevant data; otherwise, include column in upload.
  3:
    implemented: 1
    deprecated: 0
    level: error
    label: patient_added
    description: Patient ID added.
    action: Please confirm that patient was meant to be added
  4:
    implemented: 1
    deprecated: 0
    level: warning
    label: patient_removed
    description: Patient ID removed.
    action: Please confirm that patient was meant to be removed
  5:
    implemented: 1
    deprecated: 0
    level: warning
    label: sample_added
    description: Sample ID added.
    action: Please confirm that sample was meant to be added
  6:
    implemented: 1
    deprecated: 0
    level: warning
    label: sample_removed
    description: Sample ID removed.
    action: Please confirm that sample was meant to be removed
  7:
    implemented: 1
    deprecated: 0
    level: error
    label: empty_row
    description: Row entries are all missing.
    action: Please remove row from upload file.
  8:
    implemented: 1
    deprecated: 0
    level: error
    label: missing_sample_id
    description: Sample ID is missing.
    action: Please fill in missing sample ID.
  9:
    implemented: 1
    deprecated: 0
    level: warning
    label: col_empty
    description: Column values are all missing.
    action: Please confirm that site has no data for the column.  
  10:
    implemented: 0
    deprecated: 1
    deprecation_note: now using scope of release not the REDCap data dictionary as the ground truth
    level: error
    label: col_data_type_dd_mismatch
    description: Column data type does not match data type specified in data dictionary.
    action: Please check values for column and ensure that they match the appropriate data type.
  11:
    implemented: 0
    deprecated: 1
    deprecation_note: now using scope of release not the REDCap data dictionary as the ground truth
    level: error
    label: col_entry_data_type_dd_mismatch
    description: Entry data type does not match data type specified in data dictionary.
    action: Please check value for column and ensure that it matches the appropriate data type.
  12:
    implemented: 1
    deprecated: 0
    level: error
    label: col_data_type_sor_mismatch
    description: Column data type does not match data type specified in scope of release.
    action: Please check values for column and ensure that they match the appropriate data type.
  13:
    implemented: 1
    deprecated: 0
    level: error
    label: col_entry_data_type_sor_mismatch
    description: Entry data type does not match data type specified in scope of release.
    action: Please check value for column and ensure that it matches the appropriate data type.
  14:
    implemented: 1
    deprecated: 0
    level: error
    label: no_mapped_diag
    description: Mapped diagnosis is missing.
    action: Please fill in missing diagnosis.
  15:
    implemented: 1
    deprecated: 0
    level: warning
    label: rows_added
    description: Row added.
    action: Please confirm that row was meant to be added.
  16:
    implemented: 1
    deprecated: 0
    level: warning
    label: rows_removed
    description: Row removed.
    action: Please confirm that row was meant to be removed.
  17:
    implemented: 1
    deprecated: 0
    level: error
    label: sample_not_in_main_genie
    description: Sample ID does not match any ID on the main GENIE sample list.
    action: Please correct or remove sample ID.
  18:
    implemented: 1
    deprecated: 0
    level: error
    label: patient_not_in_main_genie
    description: Patient ID does not match any ID on the main GENIE patient list.
    action: Please correct or remove patient ID.
  19:
    implemented: 1
    deprecated: 0
    level: warning
    label: col_data_datetime_format_mismatch
    description: Column timestamps are not formatted correctly.
    action: Please correct the format of the timestamps to 'YYYY-mm-dd HH:MM:SS'.
  20:
    implemented: 1
    deprecated: 0
    level: error
    label: col_entry_datetime_format_mismatch
    description: Timestamp value is not formatted correctly.
    action: Please correct the format of the timestamp to 'YYYY-mm-dd HH:MM:SS'.
  21:
    implemented: 1
    deprecated: 0
    level: warning
    label: col_data_date_format_mismatch
    description: Column dates are not formatted correctly.
    action: Please correct the format of the dates to 'YYYY-mm-dd'.
  22:
    implemented: 1
    deprecated: 0
    level: error
    label: col_entry_date_format_mismatch
    description: Date value is not formatted correctly.
    action: Please correct the format of the date to 'YYYY-mm-dd'.
  23:
    implemented: 1
    deprecated: 0
    level: error
    label: col_empty_but_required
    description: Column values are all missing for required column.
    action: Please fill in required data, if applicable.  
  24:
    implemented: 1
    deprecated: 0
    level: warning
    label: col_table_not_sor
    description: Column found in table but not the scope of release.
    action: Please remove column from table.
  25:
    implemented: 1
    deprecated: 0
    level: error
    label: col_sor_not_table
    description: Column found in the scope of release but not the table.
    action: Please confirm that column has no relevant data; otherwise, include column in table.
  26:
    implemented: 1
    deprecated: 0
    level: error
    label: patient_marked_removed_from_bpc
    description: Patient has been marked as removed from BPC.
    action: Please remove the patient and all associated data from the dataset.
  27:
    implemented: 1
    deprecated: 0
    level: error
    label: sample_marked_removed_from_bpc
    description: Sample has been marked as removed from BPC.
    action: Please remove the sample and all associated data from the dataset.
  28:
    implemented: 1
    deprecated: 0
    level: warning
    label: patient_count_too_small
    description: Current case count is less than target count.
    action: Please add cases to meet target.
  29:
    implemented: 1
    deprecated: 0
    level: error
    label: investigational_drug_duration
    description: Investigational drug duration is greater than 1 day.
    action: Please adjust start and end dates of drug duration to be the same day.
  30:
    implemented: 1
    deprecated: 0
    level: error
    label: investigational_drug_other_name
    description: Investigational drug has the other drug column filled in.
    action: Please remove the name in the other drug column.
  31:
    implemented: 1
    deprecated: 0
    level: error
    label: investigational_drug_not_ct
    description: Investigational drug is not marked as being in a clinical trial.
    action: Please indicate that the investigational drug is in a clinical trial.
  32:
    implemented: 1
    deprecated: 0
    level: warning
    label: drug_not_fda_approved
    description: Drug does not have a valid associated FDA approval year in HemOnc.
    action: Please review the drug instance and determine if the drug name needs to be masked.
  33:
    implemented: 1
    deprecated: 0
    level: warning
    label: irr_sample
    description: Sample ID looks like an IRR sample.
    action: Please remove sample if IRR analyses are no longer relevant.
  34:
    implemented: 1
    deprecated: 0
    level: warning
    label: irr_patient
    description: Patient ID looks like an IRR patient.  
    action: Please remove patient if IRR analyses are no longer relevant.
  35:
    implemented: 1
    deprecated: 0
    level: warning
    label: col_empty_site_not_others
    description: Column is empty for site but not for other sites.
    action: Please confirm that site has no data for the column.
  36:
    implemented: 1
    deprecated: 0
    level: error
    label: col_five_perc_inc_missing
    description: Column had a greater than 5% increase in missingness since last upload.
    action: Please ensure that 5% increase in missing values is expected.
  37:
    implemented: 1
    deprecated: 0
    level: warning
    label: col_five_perc_dec_missing
    description: Column had a greater than 5% decrease in missingness since last upload.
    action: Please ensure that 5% decrease in missing values is expected.
  38:
    implemented: 1
    deprecated: 0
    level: error
    label: col_removed
    description: Column removed since last upload.
    action: Please ensure that column was intentionally removed.
  39:
    implemented: 1
    deprecated: 0
    level: warning
    label: col_added
    description: Column added since last upload.
    action: Please ensure that column was intentionally added.
  40:
    implemented: 1
    deprecated: 0
    level: warning
    label: file_added
    description: File added since last release.
    action: Please ensure that file was intentionally added.
  41:
    implemented: 1
    deprecated: 0
    level: error
    label: file_removed
    description: File removed since last release.
    action: Please ensure that file was intentionally removed.
  42:
    implemented: 1
    deprecated: 0
    level: error
    label: required_not_uploaded
    description: Required variable was not uploaded.
    action: Please add the required variable to the dataset.
  43:
    implemented: 1
    deprecated: 0
    level: warning
    label: ct_drug_not_investigational
    description: Drug on a clinical trial regimen is not masked as an Investigational Drug. 
    action: Please mask the drug name with the Investigational Drug label.
  44:
    implemented: 1
    deprecated: 0
    level: fail
    label: file_not_csv
    description: The file does not appear to be a CSV file.
    action: Please check the file format and ensure the correct data was uploaded.
  45:
    implemented: 1
    deprecated: 0
    level: fail
    label: data_header_col_mismatch
    description: The number of columns in the data and header files do not match.
    action: Please check the data and header files have the same corresponding columns.  
  46:
    implemented: 1
    deprecated: 1
    level: warning
    label: current_count_not_target
    description: Current case count does not match target count.
    action: Please add or remove cases to match target.
  47:
    implemented: 1
    deprecated: 0
    level: warning
    label: patient_count_too_large
    description: Current case count is greater than target count.
    action: Please remove cases to meet target.
  48:
    implemented: 1
    deprecated: 0
    level: error
    label: cpt_sample_type_numeric
    description: cpt_sample_type is numeric instead of text.
    action: Please replace numeric value with appropriate text label.
  49:
    implemented: 1
    deprecated: 0
    level: fail
    label: quac_required_column_missing
    description: File must contain column but column not found.
    action: Please ensure this column is included. 
  50: 
    implemented: 1
    deprecated: 0
    level: error
    label: invalid_choice_code
    description: The selected value does not match value choices in the data dictionary.
    action: Please confirm selected value matches a valid choice.
  51: 
    implemented: 1
    deprecated: 0
    level: error
    label: less_than_adjusted_target
    description: Case count is less than adjusted target count.
    action: Please confirm case count and submit any retracted samples.  
  52: 
    implemented: 1
    deprecated: 0
    level: error
    label: greater_than_adjusted_target
    description: Case count is greater than adjusted target count.
    action: Please confirm case count. 
  53: 
    implemented: 1
    deprecated: 0
    level: error
    label: character_double_value
    description: Column contains characters converted to doubles.
    action: Please check to ensure values match uploaded data.  
  54:
    implemented: 1
    deprecated: 0
    level: error
    label: patient_removed_not_retracted
    description: Patient ID removed but not retracted.
    action: Please confirm that patient was meant to be removed and submit via retraction form.
  55:
    implemented: 1
    deprecated: 1
    level: error
    label: sample_removed_not_retracted
    description: Sample ID removed but not retracted.
    action: Please confirm that sample was meant to be removed and submit via retraction form.
